services:
  sheqsnap:
    image: sheqsnap:latest
    container_name: sheqsnap
    restart: unless-stopped
    environment:
      DATABASE_URL: "file:/data/prod.db"
      NEXTAUTH_SECRET: "sheqsnap-secret-key-2024-production"
      NEXTAUTH_URL: "https://sheqsnap.vandilizer.online"
      VANTECH_LICENSE_URL: "http://192.168.1.106:3030"
      VANTECH_API_KEY: "demo-vantech-api-key-2026"
      AWS_REGION: ${AWS_REGION:-af-south-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:-sheqsnap}
      NEXT_PUBLIC_S3_PUBLIC_URL: ${NEXT_PUBLIC_S3_PUBLIC_URL:-https://sheqsnap.s3.af-south-1.amazonaws.com}
      S3_TENANT_PREFIX: "qa"
      NEXT_PUBLIC_DEMO_MODE: "true"
      NEXT_PUBLIC_DEMO_PASSWORD: ${NEXT_PUBLIC_DEMO_PASSWORD:-Demo@2026}
      NEXT_PUBLIC_LICENSE_SERVER_URL: ${NEXT_PUBLIC_LICENSE_SERVER_URL:-http://192.168.1.106:3030}
    volumes:
      - /opt/sheqsnap/data:/data
    ports:
      - "3002:3000"
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
