import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { writeAuditLog } from "@/lib/utils";

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const locations = await (prisma as any).chemicalLocation.findMany({
    where: { chemicalId: params.id },
    orderBy: { createdAt: "asc" },
  });

  return NextResponse.json(locations);
}

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const user = session.user as any;
  const body = await req.json();

  // Verify chemical exists
  const chemical = await (prisma as any).chemical.findUnique({ where: { id: params.id } });
  if (!chemical) return NextResponse.json({ error: "Chemical not found" }, { status: 404 });

  const location = await (prisma as any).chemicalLocation.create({
    data: {
      chemicalId: params.id,
      locationName: body.locationName,
      buildingArea: body.buildingArea || null,
      quantity: body.quantity !== undefined ? body.quantity : null,
      unit: body.unit || "kg",
      maxQuantity: body.maxQuantity !== undefined ? body.maxQuantity : null,
      storageConditions: body.storageConditions || null,
      // qrToken is auto-generated by Prisma @default(cuid())
    },
  });

  await writeAuditLog("Chemical", params.id, "LOCATION_ADD", user.id, {
    locationId: location.id,
    locationName: location.locationName,
  });

  return NextResponse.json(location, { status: 201 });
}
